; Copyright (C) 2013-2015 Wataha.net
; All Rights Reserved
;
; LICENSE Creative Commons BY-NC-ND 4.0
; See LICENSE.TXT
;
; Main developer:
;	Andrzej (akasei) Adamczyk [e-mail: akasei from wataha.net]
;-------------------------------------------------------------------------------

; Use:
; nasm - http://www.nasm.us/

%define	VARIABLE_KERNEL_VERSION		"0.464"

VARIABLE_KERNEL_PHYSICAL_ADDRESS	equ	0x0000000000100000

VARIABLE_MEMORY_PAGE_SIZE		equ	0x1000
VARIABLE_MEMORY_HIGH_ADDRESS		equ	0xFFFF000000000000
VARIABLE_MEMORY_HIGH_REAL_ADDRESS	equ	0xFFFF800000000000
VARIABLE_MEMORY_HIGH_VIRTUAL_ADDRESS	equ	VARIABLE_MEMORY_HIGH_REAL_ADDRESS - VARIABLE_MEMORY_HIGH_ADDRESS
VARIABLE_MEMORY_PML4_RECORD_SIZE	equ	VARIABLE_MEMORY_HIGH_VIRTUAL_ADDRESS / 256
; adres umowny, jest to przestrzeń gdzie jądro systemu może operować na
; różnej wielkości fragmentach pamięci logicznej, gdzie pamięć fizyczna
; nie sięga
VARIABLE_MEMORY_FREE_LOGICAL_ADDRESS	equ	0x0000400000000000

VARIABLE_KERNEL_STACK_ADDRESS		equ	VARIABLE_MEMORY_HIGH_VIRTUAL_ADDRESS - 0x1000

VARIABLE_ASCII_CODE_TERMINATOR		equ	0x00
VARIABLE_ASCII_CODE_ENTER		equ	0x0D
VARIABLE_ASCII_CODE_NEWLINE		equ	0x0A
VARIABLE_ASCII_CODE_BACKSPACE		equ	0x08
VARIABLE_ASCII_CODE_SPACE		equ	0x20

VARIABLE_COLOR_DEFAULT			equ	0x00AAAAAA
VARIABLE_COLOR_WHITE			equ	0x00FFFFFF
VARIABLE_COLOR_GREEN			equ	0x001CC76A
VARIABLE_COLOR_BLUE			equ	0x00267BE6
VARIABLE_COLOR_BLUE_LIGHT		equ	0x00469BFF
VARIABLE_COLOR_RED			equ	0x00E62626
VARIABLE_COLOR_GRAY			equ	0x00686868
VARIABLE_COLOR_ORANGE			equ	0x00FFA500

VARIABLE_COLOR_BACKGROUND_DEFAULT	equ	0x00000000

%define	VARIABLE_FONT_MATRIX_DEFAULT	"font/sinclair.asm"

VARIABLE_PCI_CONFIG_ADDRESS		equ	0x0CF8
VARIABLE_PCI_CONFIG_DATA		equ	0x0CFC

VARIABLE_PIT_CLOCK_HZ			equ	1000	; Hz

VARIABLE_KEYBOARD_CACHE_SIZE		equ	16	; / 2 = 8 znaków

VARIABLE_PROCESS_LIMIT			equ	256

VARIABLE_EMPTY				equ	0

VARIABLE_TRUE				equ	1
VARIABLE_FALSE				equ	0

VARIABLE_CMOS_PORT_IN			equ	0x71
VARIABLE_CMOS_PORT_OUT			equ	0x70
